call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the
" following enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" Incompatibilità con VI
set nocompatible

" Settaggi per i filetype
filetype on
filetype plugin on
filetype indent on

" Evidenziazione sintassi
syntax on

set hidden

" Scorciatoia per editare questo file
nmap <silent> ,ev :e $MYVIMRC<cr>

" Scorciatoia per passare alla directory del buffer in esecuzione
nmap ,cd :lcd %:h

" Scorciatoia per NERDTree
nmap ,nt :NERDTree<Enter>

" Scorciatoia per il plugin Symfony
nmap <silent> <F8> :SfSwitchView<cr>

" Scorciatoie per HTML
nmap ;img i<img src="" alt="" border="0" /><Esc>bbbbbbbgei

nmap ;link i<a href=""></a><Esc>F<i

" Riarrangiamento finestre
map ;wa <C-W>v <C-W>l <C-W>110\| <C-W>s <C-W>h <C-W>s <C-W>l

" Settaggi per la ricerca
set hlsearch
set wrapscan
set incsearch

" Visual bell
set noerrorbells
set visualbell t_vb=

" Visualizzare sempre la status line
set laststatus=2

" Nascondere il puntatore quando si scrive
set mousehide

" Nascondere elementi della GUI
set guioptions=ac

" Quando la pagina scrolla tenere il cursore a tot distanza dai bordi
set scrolloff=6

" Permette al cursore di muoversi anche dove non sono stati scritti caratteri
set virtualedit=all

" Numero di caratteri ammessi per ogni linea (a capo automatico)
set textwidth=80
set wm=6
set linebreak
set wrap

" Completamento del testo
set complete=.,w,b,t

" Fold
set foldcolumn=1

filetype plugin indent on
colorscheme desert
set softtabstop=4
set expandtab
set shiftwidth=4
set autoindent

noremap <leader>o <Esc>:CommandT<CR>
noremap <leader>O <Esc>:CommandTFlush<CR>
noremap <leader>m <Esc>:CommandTBuffer<CR>
